### ISSUE TITLE
what colorspace does smoothie use

### ISSUE THREAD

**Issue by githubpub900** [couleur-tweak-tips/smoothie-rs#39] opened 2023-11-15 17:37 UTC

**Comment by githubpub900** [comment] 2023-11-15 17:38
i tried sRGB, and made a post about this earlier, and i was told to try advanced colorspaces, how do i do that, and what colorspace do i use

**Comment by couleurm** [comment] 2023-11-16 10:12
honestly i dont even know what cursed pact i made with color demons to make this work just try out 1 second long recording yourself and see what crashes and not crashes

also refer to this https://github.com/couleur-tweak-tips/smoothie-rs/blob/main/target/jamba.vpy

for my usecase sRGB Limited works fine..?

**Comment by couleurm** [comment] 2023-11-27 11:17
duplicate of #36

**Closed by couleurm** 2023-11-27 11:17 UTC
